name: "CI / Tag"

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  use-library-js-tag:
    permissions:
      contents: write
      actions: write
      checks: write
    uses: ./.github/workflows/release.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
